apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: newsclassify-app
        image: 779846825798.dkr.ecr.eu-north-1.amazonaws.com/newsclassify-app:latest
        ports:
        - containerPort: 5001
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "1"
        env:
        - name: NEWSCLASSIFY
          valueFrom:
            secretKeyRef:
              name: newsclassify-secret
              key: NEWSCLASSIFY

---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: LoadBalancer
  selector:
    app: flask-app
  ports:
    - name: http
      protocol: TCP
      port: 5001
      targetPort: 5001